repos:
  - repo: https://github.com/pagopa/dx
    rev: pre_commit_scripts@0.0.1
    hooks:
      - id: lock_modules
        exclude: ^.*/(_modules|modules|\.terraform)(/.*)?$
        # Configure the paths to your Terraform configurations
        files: infra/(_modules|prod|src) 

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tfsec
        files: ^infra/
        args:
          - --args=--exclude-downloaded-modules
      # Disabling due to incompatibility with new module
      # oriented repository structure
      # - id: terraform_validate
      #   args:
      #     - --init-args=-lockfile=readonly
      #     - --args=-json
      #     - --args=-no-color
