packages:
  - packages/*
  - apps/*

catalog:
  prettier: ^3.5.3
  '@pagopa/io-functions-commons': ^30.0.0

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

packageImportMethod: clone-or-copy
