packages:
  - packages/*
  - apps/*

catalog:
  axios: ^1.6.5
  prettier: ^3.5.3
  '@pagopa/io-functions-commons': ^30.0.0
  '@azure/functions': ^4.11.2
  '@types/node': ^22
  '@azure/storage-blob': ^12.31.0
  '@vitest/coverage-v8': ^3.1.2
  'io-ts-types': ^0.5.19
  'vitest': ^3.1.2

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

packageImportMethod: clone-or-copy
