packages:
  - packages/*
  - apps/*

catalog:
  axios: ^1.6.5
  prettier: ^3.5.3
  '@asteasolutions/zod-to-openapi': ^8.5.0
  '@pagopa/io-functions-commons': ^30.0.0
  '@azure/functions': ^4.11.2
  '@types/node': ^22
  '@azure/storage-blob': ^12.31.0
  '@vitest/coverage-v8': ^3.1.2
  'io-ts-types': ^0.5.19
  'neverthrow': ^8.2.0
  'fastify': ^5.8.4
  'shx': ^0.3.4
  'tsx': ^4.19.2
  'vitest': ^3.1.2
  'yaml': ^2.6.0
  'zod': ^4.0.0

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

packageImportMethod: clone-or-copy
