/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const PaymentServiceProviderR = t.interface({});

// optional attributes
const PaymentServiceProviderO = t.partial({
  abiCode: t.string,

  businessRegisterNumber: t.string,

  legalRegisterName: t.string,

  legalRegisterNumber: t.string,

  vatNumberGroup: t.boolean
});

export const PaymentServiceProvider = t.exact(
  t.intersection(
    [PaymentServiceProviderR, PaymentServiceProviderO],
    "PaymentServiceProvider"
  )
);

export type PaymentServiceProvider = t.TypeOf<typeof PaymentServiceProvider>;
