/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const PspDataResourceR = t.interface({});

// optional attributes
const PspDataResourceO = t.partial({
  abiCode: t.string,

  businessRegisterNumber: t.string,

  legalRegisterName: t.string,

  legalRegisterNumber: t.string,

  vatNumberGroup: t.boolean
});

export const PspDataResource = t.exact(
  t.intersection([PspDataResourceR, PspDataResourceO], "PspDataResource")
);

export type PspDataResource = t.TypeOf<typeof PspDataResource>;
