openapi: 3.0.3
info:
  title: External Clients Definitions
paths:
  /services/{serviceId}/keys/{keyType}:
    put:
      tags:
        - service-authorization
      summary: Regenerate service key
      description: Regenerate service key by service ID and key type
      operationId: regenerateServiceKey
      parameters:
        - name: serviceId
          in: path
          description: ID of the service
          required: true
          schema:
            type: string
        - name: keyType
          in: path
          description: Key type
          required: true
          schema:
            $ref: '#/components/schemas/SubscriptionKeyType'
      responses:
        '200':
          description: Service key regenerated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionKeys'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '429':
          description: Too many requests
        '500':
          description: Internal server error

components:
  schemas:
    SubscriptionKeys:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-services-cms/master/packages/io-services-cms-models/openapi/services-cms-schemas.yaml#/SubscriptionKeys'
    SubscriptionKeyType:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-services-cms/master/packages/io-services-cms-models/openapi/services-cms-schemas.yaml#/SubscriptionKeyType'
