services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    init: true
    command: sleep infinity
    depends_on:
      cosmosdb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-migrations:
        condition: service_completed_successfully
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      CMS_COSMOSDB_CONNECTION_STRING: AccountEndpoint=http://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      CMS_COSMOSDB_CONTAINER_SERVICES_LIFECYCLE: services-lifecycle
      CMS_COSMOSDB_CONTAINER_SERVICES_PUBLICATION: services-publication
      CMS_COSMOSDB_NAME: db-services-cms
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      HOST: 0.0.0.0
      NODE_ENV: development
      PORT: 3000
      POSTGRES_DATABASE: reviewer
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${LOCAL_POSTGRES_APP_PASSWORD:-local}
      POSTGRES_PORT: 5432
      POSTGRES_SSL_ENABLED: 'false'
      POSTGRES_USER: reviewerusr
      TOPIC_SCHEMA: taxonomy
      TOPIC_TABLE: topic
    volumes:
      - .:/workspace:cached
    networks:
      - local
