FROM mcr.microsoft.com/devcontainers/base:debian@sha256:6155a486f236fd5127b76af33086029d64f64cf49dd504accb6e5f949098eb7e

# Add aliases
RUN echo 'alias ll="ls -la"' >> /etc/bash.bashrc

CMD ["sleep", "infinity"]
