/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import testLogo from "!url-loader!../data/test-logo.png";
import { getConfiguration } from "@/config";
import { faker } from "@faker-js/faker/locale/it";
import { HttpResponse, http } from "msw";

faker.seed(1);

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseURL = configuration.CDN_URLL;

  return [
    http.get(
      baseURL + configuration.SERVICES_LOGO_PATH + ":image",
      async () => {
        const imageBuffer = await fetch(testLogo as any).then(res =>
          res.arrayBuffer()
        );

        const resultArray = [
          new HttpResponse(imageBuffer, {
            status: 200,
            headers: {
              "Content-Length": imageBuffer.byteLength.toString(),
              "Content-Type": "image/png"
            }
          }),
          new HttpResponse(null, {
            status: 404
          }),
          new HttpResponse(null, {
            status: 500
          })
        ];

        return resultArray[0];
      }
    )
  ];
};
