/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import testLogo from "!url-loader!../data/test-logo.png";
import { getConfiguration } from "@/config";
import { faker } from "@faker-js/faker/locale/it";
import { rest } from "msw";

faker.seed(1);

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseURL = configuration.CDN_URL;

  return [
    rest.get(
      baseURL + configuration.SERVICES_LOGO_PATH + ":image",
      async (_, res, ctx) => {
        const imageBuffer = await fetch(testLogo as any).then(res =>
          res.arrayBuffer()
        );

        const resultArray = [
          [
            ctx.set("Content-Length", imageBuffer.byteLength.toString()),
            ctx.set("Content-Type", "image/png"),
            ctx.body(imageBuffer)
          ],
          [ctx.status(404)],
          [ctx.status(500)]
        ];

        return res(...resultArray[0]);
      }
    )
  ];
};
