/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { getConfiguration } from "@/config";
import { HttpResponse, http } from "msw";

import { aMockErrorResponse } from "../data/common-data";
import {
  aMockServiceLifecycleBulkFetchDocuments,
  aMockServicesLifecycleCollection,
  aMockServicesLifecyclePkranges,
  info,
} from "../data/cosmos-data";

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseUrl = new URL(configuration.COSMOSDB_URI).href;

  return [
    http.get(
      baseUrl,
      (_) =>
        new HttpResponse(JSON.stringify(info), {
          status: 200,
        }),
    ),
    http.get(
      `${baseUrl}dbs/db-services-cms/colls/services-lifecycle`,
      (_) =>
        new HttpResponse(JSON.stringify(aMockServicesLifecycleCollection), {
          status: 200,
        }),
    ),
    http.get(
      `${baseUrl}dbs/db-services-cms/colls/services-lifecycle/pkranges`,
      (_) =>
        new HttpResponse(JSON.stringify(aMockServicesLifecyclePkranges), {
          status: 200,
        }),
    ),
    http.get(`${baseUrl}dbs/db-services-cms/colls/services-publication`, (_) =>
      HttpResponse.json({
        ...aMockServicesLifecycleCollection,
        id: "services-publication",
      }),
    ),
    http.get(
      `${baseUrl}dbs/db-services-cms/colls/services-publication/pkranges`,
      (_) => HttpResponse.json(aMockServicesLifecyclePkranges),
    ),
    http.post(
      `${baseUrl}dbs/db-services-cms/colls/services-lifecycle/docs`,
      async ({ request }) => {
        const reqBody = await request.json();
        if (Array.isArray(reqBody)) {
          const resBody = reqBody.map((operation) =>
            aMockServiceLifecycleBulkFetchDocuments(operation.id),
          );
          return new HttpResponse(JSON.stringify(resBody), {
            status: 200,
          });
        }
        return new HttpResponse(JSON.stringify(get500Response()), {
          status: 500,
        });
      },
    ),
    http.post(
      `${baseUrl}dbs/db-services-cms/colls/services-publication/docs`,
      async ({ request }) => {
        const reqBody = await request.json();
        return new HttpResponse(
          JSON.stringify(
            Array.isArray(reqBody)
              ? reqBody.map(() => ({ requestCharge: 1, statusCode: 404 }))
              : get500Response(),
          ),
          { status: Array.isArray(reqBody) ? 200 : 500 },
        );
      },
    ),
  ];
};

function get500Response() {
  return aMockErrorResponse;
}
