/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { getConfiguration } from "@/config";
import { http } from "msw";
import { aMockErrorResponse } from "../data/common-data";

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseUrl = new URL(configuration.LEGACY_COSMOSDB_URI).href;

  return [
    // http.get(baseUrl, (req, res, ctx) => {
    //   const resultArray = [
    //     [ctx.status(200), ctx.json({})],
    //     [ctx.status(500), ctx.json(getWellKnown500Response())]
    //   ];
    //   return res(...resultArray[0]);
    // })
    // http.post(
    //   "https://io-p-cosmos-api.documents.azure.com/dbs/db/colls/subscription-cidrs/docs",
    //   async (req, res, ctx) => {
    //     console.log("REQUEST BODY", await req.json());
    //     const resultArray = [
    //       [ctx.status(200), ctx.json({})],
    //       [ctx.status(500), ctx.json(getWellKnown500Response())]
    //     ];
    //     return res(...resultArray[0]);
    //   }
    // )
  ];
};

export function getWellKnown500Response() {
  return aMockErrorResponse;
}
