/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { getConfiguration } from "@/config";
import { faker } from "@faker-js/faker/locale/it";
import { rest } from "msw";
import { aMockErrorResponse } from "../data/common-data";
import {
  aWellKnown,
  getMockInstitution,
  getSelfCareProblemResponse
} from "../data/selfcare-data";

faker.seed(1);

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseURL = configuration.SELFCARE_EXTERNAL_API_BASE_URL;

  return [
    rest.get(configuration.SELFCARE_JWKS_URL, (_, res, ctx) => {
      const resultArray = [
        [ctx.status(200), ctx.json(getWellKnown200Response())],
        [ctx.status(500), ctx.json(getWellKnown500Response())]
      ];

      return res(...resultArray[0]);
    }),
    rest.get(`${baseURL}/institutions`, (_, res, ctx) => {
      const resultArray = [
        [ctx.status(200), ctx.json([getMockInstitution()])],
        [ctx.status(404), ctx.json(getSelfCareProblemResponse(404))],
        [ctx.status(500), ctx.json(getSelfCareProblemResponse(500))]
      ];
      return res(...resultArray[0]);
    }),
    rest.get(`${baseURL}/institutions/:institutionId`, (req, res, ctx) => {
      const { institutionId } = req.params;
      const resultArray = [
        [
          ctx.status(200),
          ctx.json(getMockInstitution(institutionId as string))
        ],
        [ctx.status(404), ctx.json(getSelfCareProblemResponse(404))],
        [ctx.status(500), ctx.json(getSelfCareProblemResponse(500))]
      ];

      return res(...resultArray[0]);
    })
  ];
};

export function getWellKnown200Response() {
  return aWellKnown;
}

export function getWellKnown500Response() {
  return aMockErrorResponse;
}
