/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { getConfiguration } from "@/config";
import { faker } from "@faker-js/faker/locale/it";
import { rest } from "msw";
import { aMockErrorResponse } from "../data/common-data";
import { aWellKnown } from "../data/selfcare-data";

const MAX_ARRAY_LENGTH = 20;

faker.seed(1);

export const buildHandlers = () => {
  const configuration = getConfiguration();
  const baseURL = configuration.SELFCARE_BASE_URL;

  return [
    rest.get(baseURL + configuration.SELFCARE_JWKS_PATH, (_, res, ctx) => {
      const resultArray = [
        [ctx.status(200), ctx.json(getWellKnown200Response())],
        [ctx.status(500), ctx.json(getWellKnown500Response())]
      ];

      return res(...resultArray[0]);
    })
  ];
};

export function getWellKnown200Response() {
  return aWellKnown;
}

export function getWellKnown500Response() {
  return aMockErrorResponse;
}
