/**
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { faker } from "@faker-js/faker/locale/it";
import { rest } from "msw";
import { aMockErrorResponse } from "../data/common-data";
import { aWellKnown } from "../data/selfcare-data";
import {
  getDelegatesByOrganizationMockResponse,
  getLatestOwnershipClaimStatusMockResponse,
  getOwnershipClaimStatusMockResponse
} from "../data/subscriptions-migration-data";

faker.seed(new Date().getTime());

export const buildHandlers = () => {
  const baseURL = process.env.SUBSCRIPTION_MIGRATIONS_URL;

  return [
    rest.get(
      `${baseURL}/organizations/:organizationFiscalCode/ownership-claims/latest`,
      (_, res, ctx) => {
        const resultArray = [
          [
            ctx.status(200),
            ctx.json(getLatestOwnershipClaimStatusMockResponse())
          ],
          [ctx.status(500)]
        ];

        return res(...resultArray[0]);
      }
    ),
    rest.get(
      `${baseURL}/organizations/:organizationFiscalCode/ownership-claims/:delegateId`,
      (_, res, ctx) => {
        const resultArray = [
          [ctx.status(200), ctx.json(getOwnershipClaimStatusMockResponse())],
          [ctx.status(404)],
          [ctx.status(500)]
        ];
        return res(...resultArray[0]);
      }
    ),
    rest.post(
      `${baseURL}/organizations/:organizationFiscalCode/ownership-claims/:delegateId`,
      (_, res, ctx) => {
        const resultArray = [
          [ctx.status(201)],
          [ctx.status(404)],
          [ctx.status(500)]
        ];
        return res(...resultArray[0]);
      }
    ),
    rest.get(
      `${baseURL}/organizations/:organizationFiscalCode/delegates`,
      (_, res, ctx) => {
        const resultArray = [
          [ctx.status(200), ctx.json(getDelegatesByOrganizationMockResponse())],
          [ctx.status(404)],
          [ctx.status(500)]
        ];
        return res(...resultArray[0]);
      }
    )
  ];
};

export function getWellKnown200Response() {
  return aWellKnown;
}

export function getWellKnown500Response() {
  return aMockErrorResponse;
}
