/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const AckPayloadRequestR = t.interface({
  message: t.string
});

// optional attributes
const AckPayloadRequestO = t.partial({});

export const AckPayloadRequest = t.exact(
  t.intersection([AckPayloadRequestR, AckPayloadRequestO], "AckPayloadRequest")
);

export type AckPayloadRequest = t.TypeOf<typeof AckPayloadRequest>;
