/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const AssistanceContactsResourceR = t.interface({});

// optional attributes
const AssistanceContactsResourceO = t.partial({
  supportEmail: t.string,

  supportPhone: t.string
});

export const AssistanceContactsResource = t.exact(
  t.intersection(
    [AssistanceContactsResourceR, AssistanceContactsResourceO],
    "AssistanceContactsResource"
  )
);

export type AssistanceContactsResource = t.TypeOf<
  typeof AssistanceContactsResource
>;
