/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const AttributesResponseR = t.interface({});

// optional attributes
const AttributesResponseO = t.partial({
  code: t.string,

  description: t.string,

  origin: t.string
});

export const AttributesResponse = t.exact(
  t.intersection(
    [AttributesResponseR, AttributesResponseO],
    "AttributesResponse"
  )
);

export type AttributesResponse = t.TypeOf<typeof AttributesResponse>;
