/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const AttributeR = t.interface({});

// optional attributes
const AttributeO = t.partial({
  origin: t.string,

  code: t.string,

  description: t.string
});

export const Attribute = t.exact(
  t.intersection([AttributeR, AttributeO], "Attribute")
);

export type Attribute = t.TypeOf<typeof Attribute>;
