/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { Attribute } from "./Attribute";

export type Attributes = t.TypeOf<typeof Attributes>;
export const Attributes = t.readonlyArray(Attribute, "array of Attribute");
