/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const BillingResponseR = t.interface({});

// optional attributes
const BillingResponseO = t.partial({
  publicServices: t.boolean,

  recipientCode: t.string,

  vatNumber: t.string
});

export const BillingResponse = t.exact(
  t.intersection([BillingResponseR, BillingResponseO], "BillingResponse")
);

export type BillingResponse = t.TypeOf<typeof BillingResponse>;
