/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const CompanyInformationsResourceR = t.interface({});

// optional attributes
const CompanyInformationsResourceO = t.partial({
  businessRegisterPlace: t.string,

  rea: t.string,

  shareCapital: t.string
});

export const CompanyInformationsResource = t.exact(
  t.intersection(
    [CompanyInformationsResourceR, CompanyInformationsResourceO],
    "CompanyInformationsResource"
  )
);

export type CompanyInformationsResource = t.TypeOf<
  typeof CompanyInformationsResource
>;
