/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const DataProtectionOfficerResponseR = t.interface({});

// optional attributes
const DataProtectionOfficerResponseO = t.partial({
  address: t.string,

  email: t.string,

  pec: t.string
});

export const DataProtectionOfficerResponse = t.exact(
  t.intersection(
    [DataProtectionOfficerResponseR, DataProtectionOfficerResponseO],
    "DataProtectionOfficerResponse"
  )
);

export type DataProtectionOfficerResponse = t.TypeOf<
  typeof DataProtectionOfficerResponse
>;
