/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum InstitutionTypeEnum {
  "GSP" = "GSP",

  "PA" = "PA",

  "PG" = "PG",

  "PSP" = "PSP",

  "PT" = "PT",

  "SCP" = "SCP",

  "SA" = "SA",

  "AS" = "AS"
}

export enum TypeEnum {
  "AOO" = "AOO",

  "PT" = "PT"
}

// required attributes
const DelegationResponseR = t.interface({});

// optional attributes
const DelegationResponseO = t.partial({
  brokerId: t.string,

  brokerName: t.string,

  brokerTaxCode: t.string,

  brokerType: t.string,

  id: t.string,

  institutionId: t.string,

  institutionName: t.string,

  institutionRootName: t.string,

  institutionType: enumType<InstitutionTypeEnum>(
    InstitutionTypeEnum,
    "institutionType"
  ),

  productId: t.string,

  taxCode: t.string,

  type: enumType<TypeEnum>(TypeEnum, "type")
});

export const DelegationResponse = t.exact(
  t.intersection(
    [DelegationResponseR, DelegationResponseO],
    "DelegationResponse"
  )
);

export type DelegationResponse = t.TypeOf<typeof DelegationResponse>;
