/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { EmailString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const DpoDataResourceR = t.interface({});

// optional attributes
const DpoDataResourceO = t.partial({
  address: t.string,

  email: EmailString,

  pec: EmailString
});

export const DpoDataResource = t.exact(
  t.intersection([DpoDataResourceR, DpoDataResourceO], "DpoDataResource")
);

export type DpoDataResource = t.TypeOf<typeof DpoDataResource>;
