/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const GeographicTaxonomyR = t.interface({
  code: t.string,

  desc: t.string
});

// optional attributes
const GeographicTaxonomyO = t.partial({});

export const GeographicTaxonomy = t.exact(
  t.intersection(
    [GeographicTaxonomyR, GeographicTaxonomyO],
    "GeographicTaxonomy"
  )
);

export type GeographicTaxonomy = t.TypeOf<typeof GeographicTaxonomy>;
