/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const GeoTaxonomiesR = t.interface({});

// optional attributes
const GeoTaxonomiesO = t.partial({
  code: t.string,

  desc: t.string
});

export const GeoTaxonomies = t.exact(
  t.intersection([GeoTaxonomiesR, GeoTaxonomiesO], "GeoTaxonomies")
);

export type GeoTaxonomies = t.TypeOf<typeof GeoTaxonomies>;
