/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { DataProtectionOfficer } from "./DataProtectionOfficer";
import { InstitutionGeographicTaxonomies } from "./InstitutionGeographicTaxonomies";
import { PaymentServiceProvider } from "./PaymentServiceProvider";
import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum InstitutionTypeEnum {
  "GSP" = "GSP",

  "PA" = "PA",

  "PG" = "PG",

  "PSP" = "PSP",

  "PT" = "PT",

  "SA" = "SA",

  "SCP" = "SCP",

  "AS" = "AS"
}

// required attributes
const InstitutionUpdateR = t.interface({});

// optional attributes
const InstitutionUpdateO = t.partial({
  address: t.string,

  businessRegisterPlace: t.string,

  dataProtectionOfficer: DataProtectionOfficer,

  description: t.string,

  digitalAddress: t.string,

  geographicTaxonomies: t.readonlyArray(
    InstitutionGeographicTaxonomies,
    "array of InstitutionGeographicTaxonomies"
  ),

  imported: t.boolean,

  institutionType: enumType<InstitutionTypeEnum>(
    InstitutionTypeEnum,
    "institutionType"
  ),

  paymentServiceProvider: PaymentServiceProvider,

  rea: t.string,

  shareCapital: t.string,

  supportEmail: t.string,

  supportPhone: t.string,

  taxCode: t.string,

  zipCode: t.string
});

export const InstitutionUpdate = t.exact(
  t.intersection([InstitutionUpdateR, InstitutionUpdateO], "InstitutionUpdate")
);

export type InstitutionUpdate = t.TypeOf<typeof InstitutionUpdate>;
