/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const InstitutionGeographicTaxonomiesR = t.interface({});

// optional attributes
const InstitutionGeographicTaxonomiesO = t.partial({
  code: t.string,

  desc: t.string
});

export const InstitutionGeographicTaxonomies = t.exact(
  t.intersection(
    [InstitutionGeographicTaxonomiesR, InstitutionGeographicTaxonomiesO],
    "InstitutionGeographicTaxonomies"
  )
);

export type InstitutionGeographicTaxonomies = t.TypeOf<
  typeof InstitutionGeographicTaxonomies
>;
