/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const InstitutionLocationDataDtoR = t.interface({
  city: t.string,

  country: t.string,

  county: t.string
});

// optional attributes
const InstitutionLocationDataDtoO = t.partial({});

export const InstitutionLocationDataDto = t.exact(
  t.intersection(
    [InstitutionLocationDataDtoR, InstitutionLocationDataDtoO],
    "InstitutionLocationDataDto"
  )
);

export type InstitutionLocationDataDto = t.TypeOf<
  typeof InstitutionLocationDataDto
>;
