/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { GeographicTaxonomyResource } from "./GeographicTaxonomyResource";
import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum InstitutionTypeEnum {
  "AS" = "AS",

  "GSP" = "GSP",

  "PA" = "PA",

  "PG" = "PG",

  "PSP" = "PSP",

  "PT" = "PT",

  "SA" = "SA",

  "SCP" = "SCP"
}

// required attributes
const InstitutionDetailResourceR = t.interface({});

// optional attributes
const InstitutionDetailResourceO = t.partial({
  address: t.string,

  aooParentCode: t.string,

  businessRegisterPlace: t.string,

  city: t.string,

  country: t.string,

  county: t.string,

  description: t.string,

  digitalAddress: t.string,

  externalId: t.string,

  geographicTaxonomies: t.readonlyArray(
    GeographicTaxonomyResource,
    "array of GeographicTaxonomyResource"
  ),

  id: t.string,

  imported: t.boolean,

  institutionType: enumType<InstitutionTypeEnum>(
    InstitutionTypeEnum,
    "institutionType"
  ),

  origin: t.string,

  originId: t.string,

  parentDescription: t.string,

  rea: t.string,

  shareCapital: t.string,

  subunitCode: t.string,

  subunitType: t.string,

  supportEmail: t.string,

  supportPhone: t.string,

  taxCode: t.string,

  zipCode: t.string
});

export const InstitutionDetailResource = t.exact(
  t.intersection(
    [InstitutionDetailResourceR, InstitutionDetailResourceO],
    "InstitutionDetailResource"
  )
);

export type InstitutionDetailResource = t.TypeOf<
  typeof InstitutionDetailResource
>;
