/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { InstitutionResponse } from "./InstitutionResponse";
import * as t from "io-ts";

// required attributes
const InstitutionsResponseR = t.interface({});

// optional attributes
const InstitutionsResponseO = t.partial({
  institutions: t.readonlyArray(
    InstitutionResponse,
    "array of InstitutionResponse"
  )
});

export const InstitutionsResponse = t.exact(
  t.intersection(
    [InstitutionsResponseR, InstitutionsResponseO],
    "InstitutionsResponse"
  )
);

export type InstitutionsResponse = t.TypeOf<typeof InstitutionsResponse>;
