/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const InvalidParamR = t.interface({
  name: t.string,

  reason: t.string
});

// optional attributes
const InvalidParamO = t.partial({});

export const InvalidParam = t.exact(
  t.intersection([InvalidParamR, InvalidParamO], "InvalidParam")
);

export type InvalidParam = t.TypeOf<typeof InvalidParam>;
