/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { BillingResponse } from "./BillingResponse";
import * as t from "io-ts";
import { UTCISODateFromString } from "@pagopa/ts-commons/lib/dates";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum StatusEnum {
  "ACTIVE" = "ACTIVE",

  "DELETED" = "DELETED",

  "PENDING" = "PENDING",

  "REJECTED" = "REJECTED",

  "SUSPENDED" = "SUSPENDED",

  "TOBEVALIDATED" = "TOBEVALIDATED"
}

// required attributes
const OnboardingResponseR = t.interface({});

// optional attributes
const OnboardingResponseO = t.partial({
  billing: BillingResponse,

  closedAt: UTCISODateFromString,

  contract: t.string,

  createdAt: UTCISODateFromString,

  pricingPlan: t.string,

  productId: t.string,

  status: enumType<StatusEnum>(StatusEnum, "status"),

  tokenId: t.string,

  updatedAt: UTCISODateFromString
});

export const OnboardingResponse = t.exact(
  t.intersection(
    [OnboardingResponseR, OnboardingResponseO],
    "OnboardingResponse"
  )
);

export type OnboardingResponse = t.TypeOf<typeof OnboardingResponse>;
