/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ProductInfo } from "./ProductInfo";
import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum InstitutionTypeEnum {
  "GSP" = "GSP",

  "PA" = "PA",

  "PG" = "PG",

  "PSP" = "PSP",

  "PT" = "PT",

  "SCP" = "SCP",

  "SA" = "SA",

  "AS" = "AS"
}

// required attributes
const OnboardedInstitutionResourceR = t.interface({});

// optional attributes
const OnboardedInstitutionResourceO = t.partial({
  address: t.string,

  description: t.string,

  digitalAddress: t.string,

  id: t.string,

  institutionType: enumType<InstitutionTypeEnum>(
    InstitutionTypeEnum,
    "institutionType"
  ),

  productInfo: ProductInfo,

  taxCode: t.string,

  zipCode: t.string
});

export const OnboardedInstitutionResource = t.exact(
  t.intersection(
    [OnboardedInstitutionResourceR, OnboardedInstitutionResourceO],
    "OnboardedInstitutionResource"
  )
);

export type OnboardedInstitutionResource = t.TypeOf<
  typeof OnboardedInstitutionResource
>;
