/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { UserGroupResource } from "./UserGroupResource";
import * as t from "io-ts";

// required attributes
const PageOfUserGroupResourceR = t.interface({});

// optional attributes
const PageOfUserGroupResourceO = t.partial({
  content: t.readonlyArray(UserGroupResource, "array of UserGroupResource"),

  number: t.Integer,

  size: t.Integer,

  totalElements: t.Integer,

  totalPages: t.Integer
});

export const PageOfUserGroupResource = t.exact(
  t.intersection(
    [PageOfUserGroupResourceR, PageOfUserGroupResourceO],
    "PageOfUserGroupResource"
  )
);

export type PageOfUserGroupResource = t.TypeOf<typeof PageOfUserGroupResource>;
