/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const PaymentServiceProviderResponseR = t.interface({});

// optional attributes
const PaymentServiceProviderResponseO = t.partial({
  abiCode: t.string,

  businessRegisterNumber: t.string,

  legalRegisterName: t.string,

  legalRegisterNumber: t.string,

  vatNumberGroup: t.boolean
});

export const PaymentServiceProviderResponse = t.exact(
  t.intersection(
    [PaymentServiceProviderResponseR, PaymentServiceProviderResponseO],
    "PaymentServiceProviderResponse"
  )
);

export type PaymentServiceProviderResponse = t.TypeOf<
  typeof PaymentServiceProviderResponse
>;
