/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { InvalidParam } from "./InvalidParam";
import * as t from "io-ts";

/**
 * A "problem detail" as a way to carry machine-readable details of errors (https://datatracker.ietf.org/doc/html/rfc7807)
 */

// required attributes
const ProblemR = t.interface({
  status: t.Integer,

  title: t.string
});

// optional attributes
const ProblemO = t.partial({
  detail: t.string,

  instance: t.string,

  invalidParams: t.readonlyArray(InvalidParam, "array of InvalidParam"),

  type: t.string
});

export const Problem = t.exact(t.intersection([ProblemR, ProblemO], "Problem"));

export type Problem = t.TypeOf<typeof Problem>;
