/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { UTCISODateFromString } from "@pagopa/ts-commons/lib/dates";

// required attributes
const ProductInfoR = t.interface({});

// optional attributes
const ProductInfoO = t.partial({
  createdAt: UTCISODateFromString,

  id: t.string,

  role: t.string
});

export const ProductInfo = t.exact(
  t.intersection([ProductInfoR, ProductInfoO], "ProductInfo")
);

export type ProductInfo = t.TypeOf<typeof ProductInfo>;
