/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { ProductRoleInfoRes } from "./ProductRoleInfoRes";
import { UTCISODateFromString } from "@pagopa/ts-commons/lib/dates";
import { PatternString } from "@pagopa/ts-commons/lib/strings";

/**
 * Mappings between Party's and Product's role
 */

// additional attributes

export const ProductResourceRoleMappings = t.record(
  t.string,

  ProductRoleInfoRes,

  "ProductResourceRoleMappings"
);

export type ProductResourceRoleMappings = t.TypeOf<
  typeof ProductResourceRoleMappings
>;

// required attributes
const ProductResourceR = t.interface({});

// optional attributes
const ProductResourceO = t.partial({
  contractTemplatePath: t.string,

  contractTemplateUpdatedAt: UTCISODateFromString,

  contractTemplateVersion: t.string,

  createdAt: UTCISODateFromString,

  depictImageUrl: t.string,

  description: t.string,

  id: t.string,

  identityTokenAudience: t.string,

  logo: t.string,

  logoBgColor: PatternString("^#0-9A-F6$"),

  parentId: t.string,

  roleManagementURL: t.string,

  roleMappings: ProductResourceRoleMappings,

  title: t.string,

  urlBO: t.string,

  urlPublic: t.string
});

export const ProductResource = t.exact(
  t.intersection([ProductResourceR, ProductResourceO], "ProductResource")
);

export type ProductResource = t.TypeOf<typeof ProductResource>;
