/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ProductRole } from "./ProductRole";
import * as t from "io-ts";

// required attributes
const ProductRoleInfoResR = t.interface({
  multiroleAllowed: t.boolean,

  roles: t.readonlyArray(ProductRole, "array of ProductRole")
});

// optional attributes
const ProductRoleInfoResO = t.partial({});

export const ProductRoleInfoRes = t.exact(
  t.intersection(
    [ProductRoleInfoResR, ProductRoleInfoResO],
    "ProductRoleInfoRes"
  )
);

export type ProductRoleInfoRes = t.TypeOf<typeof ProductRoleInfoRes>;
