/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const RootParentResourceR = t.interface({});

// optional attributes
const RootParentResourceO = t.partial({
  description: t.string,

  id: t.string
});

export const RootParentResource = t.exact(
  t.intersection(
    [RootParentResourceR, RootParentResourceO],
    "RootParentResource"
  )
);

export type RootParentResource = t.TypeOf<typeof RootParentResource>;
