/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const SearchUserDtoR = t.interface({
  fiscalCode: t.string
});

// optional attributes
const SearchUserDtoO = t.partial({});

export const SearchUserDto = t.exact(
  t.intersection([SearchUserDtoR, SearchUserDtoO], "SearchUserDto")
);

export type SearchUserDto = t.TypeOf<typeof SearchUserDto>;
