/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { EmailString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const SupportRequestDtoR = t.interface({
  email: EmailString
});

// optional attributes
const SupportRequestDtoO = t.partial({});

export const SupportRequestDto = t.exact(
  t.intersection([SupportRequestDtoR, SupportRequestDtoO], "SupportRequestDto")
);

export type SupportRequestDto = t.TypeOf<typeof SupportRequestDto>;
