/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum RoleEnum {
  "DELEGATE" = "DELEGATE",

  "MANAGER" = "MANAGER",

  "OPERATOR" = "OPERATOR",

  "SUB_DELEGATE" = "SUB_DELEGATE"
}

// required attributes
const TokenUserR = t.interface({});

// optional attributes
const TokenUserO = t.partial({
  role: enumType<RoleEnum>(RoleEnum, "role"),

  userId: t.string
});

export const TokenUser = t.exact(
  t.intersection([TokenUserR, TokenUserO], "TokenUser")
);

export type TokenUser = t.TypeOf<typeof TokenUser>;
