/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { TokenResponse } from "./TokenResponse";
import * as t from "io-ts";

// required attributes
const TokenListResponseR = t.interface({});

// optional attributes
const TokenListResponseO = t.partial({
  items: t.readonlyArray(TokenResponse, "array of TokenResponse")
});

export const TokenListResponse = t.exact(
  t.intersection([TokenListResponseR, TokenListResponseO], "TokenListResponse")
);

export type TokenListResponse = t.TypeOf<typeof TokenListResponse>;
