/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { OnboardedInstitutionResource } from "./OnboardedInstitutionResource";
import { UserResource } from "./UserResource";
import * as t from "io-ts";

// required attributes
const UserInfoResourceR = t.interface({});

// optional attributes
const UserInfoResourceO = t.partial({
  onboardedInstitutions: t.readonlyArray(
    OnboardedInstitutionResource,
    "array of OnboardedInstitutionResource"
  ),

  user: UserResource
});

export const UserInfoResource = t.exact(
  t.intersection([UserInfoResourceR, UserInfoResourceO], "UserInfoResource")
);

export type UserInfoResource = t.TypeOf<typeof UserInfoResource>;
