/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const UserResourceR = t.interface({});

// optional attributes
const UserResourceO = t.partial({
  email: t.string,

  id: t.string,

  name: t.string,

  roles: t.readonlyArray(t.string, "array of string"),

  surname: t.string,

  fiscalCode: t.string
});

export const UserResource = t.exact(
  t.intersection([UserResourceR, UserResourceO], "UserResource")
);

export type UserResource = t.TypeOf<typeof UserResource>;
