/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const UserResponseR = t.interface({});

// optional attributes
const UserResponseO = t.partial({
  email: t.string,

  id: t.string,

  name: t.string,

  surname: t.string,

  taxCode: t.string
});

export const UserResponse = t.exact(
  t.intersection([UserResponseR, UserResponseO], "UserResponse")
);

export type UserResponse = t.TypeOf<typeof UserResponse>;
