name: 'Azure Deploy'

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: io-p-services-cms-webapp-fn
  AZURE_BACKOFFICE_NAME: io-p-services-cms-backoffice-app
  RESOURCE_GROUP: io-p-services-cms-rg
  WEBAPP_HEALTHCHECK_PATH: 'api/v1/info'
  BACKOFFICE_HEALTHCHECK_PATH: 'api/info'

jobs:

  deployments:
    name: App Deployments
    runs-on: [self-hosted]
    environment: app-prod-cd

    steps:
      - name: Download artifact
        id: download_artifact
        run: 'curl --output artifact.zip --location ${{ github.event.release.assets[0].browser_download_url }}'

      - name: Identify workload
        id: workload
        shell: bash
        run: |
          # Parse the release artifact name to retrieve app name
          echo name=$(echo "${{ contains(github.event.release.assets[0].name, 'webapp') && env.AZURE_WEBAPP_NAME || env.AZURE_BACKOFFICE_NAME }}") >> "$GITHUB_OUTPUT"

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy to staging
        if: contains(github.event.release.assets[0].name, 'webapp')
        uses: azure/webapps-deploy@145a0687697df1d8a28909569f6e5d86213041f9 #v3.0.0
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: artifact.zip
          slot-name: staging
          clean: true

      - name: 'Healthcheck'
        if: contains(github.event.release.assets[0].name, 'webapp')
        id: healthcheck
        run: |
          sleep 30
          curl --retry 5 --retry-max-time 120 --retry-all-errors --fail-with-body 'https://${{ env.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net/${{ env.WEBAPP_HEALTHCHECK_PATH }}'

      - name: 'Swap staging to production'
        if: contains(github.event.release.assets[0].name, 'webapp')
        id: swap_to_production
        run: az webapp deployment slot swap -g ${{ env.RESOURCE_GROUP }} -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production

      - name: Deploy Backoffice to staging
        if: contains(github.event.release.assets[0].name, 'backoffice')
        uses: azure/webapps-deploy@145a0687697df1d8a28909569f6e5d86213041f9 #v3.0.0
        with:
          app-name: ${{ env.AZURE_BACKOFFICE_NAME }}
          package: artifact.zip
          slot-name: staging
          clean: true

      - name: 'Backoffice Healthcheck'
        if: contains(github.event.release.assets[0].name, 'backoffice')
        id: healthcheck_backoffice
        run: |
          sleep 30
          curl --retry 5 --retry-max-time 120 --retry-all-errors --fail-with-body 'https://${{ env.AZURE_BACKOFFICE_NAME }}-staging.azurewebsites.net/${{ env.BACKOFFICE_HEALTHCHECK_PATH }}'

      - name: 'Swap Backoffice staging to production'
        if: contains(github.event.release.assets[0].name, 'backoffice')
        id: swap_to_production_backoffice
        run: az webapp deployment slot swap -g ${{ env.RESOURCE_GROUP }} -n ${{ env.AZURE_BACKOFFICE_NAME }} --slot staging --target-slot production
