name: "Azure Deploy Manual"

on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        type: string
      package_url:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  ENV_SHORT: p
  FUNCTION_SLOT: staging
  PREFIX: io
  RESOURCE_GROUP: io-p-services-cms-rg

jobs:
  runner_job:
    name: Runner Job
    runs-on: ubuntu-22.04
    environment: prod-cd #### use your specific identity!
    steps:
      - name: Download artifact
        run: "curl --output artifact.zip --location ${{ github.event.inputs.package_url }}"

      #      - name: Identify workload
      #        id: workload
      #        shell: bash
      #        run: |
      #          # Parse the release artifact name to extract type, domain and name
      #          set -euo pipefail
      #
      #          echo name=$(echo "${{ github.event.inputs.name }}" | sed -En "s/^([a-z0-9\-]+).+$/\3/p" | tr -d '\n') >> "$GITHUB_OUTPUT"

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PREFIX }}-${{ env.ENV_SHORT }}-services-cms-webapp-fn
          package: artifact.zip
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          slot-name: staging
