name: Static Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - infra/**
      - .identity/**
      - .terraform-version
      - .github/workflows/infra-static-analysis.yaml

jobs:
  tf_analysis:
    uses: pagopa/dx/.github/workflows/static_analysis.yaml@main
    name: Terraform Validation
    secrets: inherit
    with:
      pre_commit_tf_tag: 'v1.97.0@sha256:d5e2233e199bd97566e20db5bbaf5f1db67edd5398660da3b61b1b6163f28ff1'
      enable_modified_files_detection: true
