name: Infra Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci.yml'

permissions:
  id-token: write
  contents: read

env:
  DIR: 'infra/src'
  AZURE_ENVIRONMENT: prod

jobs:
  create_runner:
    name: Create Runner
    runs-on: ubuntu-latest
    environment: prod-runner
    outputs:
      runner_name: ${{ steps.create_github_runner.outputs.runner_name }}
    steps:
      - name: Create GitHub Runner
        id: create_github_runner
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-create-action
        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-create-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          container_app_environment_name: ${{ secrets.AZURE_CONTAINER_APP_ENVIRONMENT_NAME }}
          resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          pat_token: ${{ secrets.BOT_TOKEN }}

  terraform_plan_job:
    name: Terraform Plan
    runs-on: [self-hosted, '${{ needs.create_runner.outputs.runner_name }}']
    environment: prod-ci
    needs: create_runner
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup terraform
        id: setup-version
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/terraform/terraform-install-action
        uses: pagopa/eng-github-actions-iac-template/terraform/terraform-install-action@main

      - name: Terraform plan
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/terraform-plan-azure-action
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-plan-azure-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}
          azure_environment: prod

  cleanup_runner:
    name: Cleanup Runner
    if: always()
    runs-on: ubuntu-latest
    environment: prod-runner
    needs: [create_runner, terraform_plan_job]
    steps:
      - name: Cleanup GitHub Runner
        id: cleanup_github_runner
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-cleanup-action
        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-cleanup-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          runner_name: ${{ needs.create_runner.outputs.runner_name }}
          pat_token: ${{ secrets.BOT_TOKEN }}
