name: Terraform apply multiregion

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"
      - ".github/workflows/infra-release-p.yml"

jobs:
  infra_release_prod_itn:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
    name: Terraform apply
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
      override_github_environment: infra-prod
