name: Infra Continuous Delivery

on:
  workflow_dispatch:
  # Trigger the workflow on push on the master branch
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      - '.github/workflows/infra-cd.yml'

permissions:
  id-token: write
  contents: read

env:
  DIR: 'infra/src'
  AZURE_ENVIRONMENT: prod

jobs:

  terraform_preapply_job:
    name: Terraform Pre Apply
    runs-on: [self-hosted]
    environment: infra-prod-ci

    steps:

      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup terraform
        id: setup-version
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/terraform/terraform-install-action
        uses: pagopa/eng-github-actions-iac-template/terraform/terraform-install-action@main

      - name: Terraform pre apply
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/terraform-preapply-azure-action
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-preapply-azure-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID_CI }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}
          azure_environment: prod

      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
        with:
          name: tfplan-output
          if-no-files-found: error
          path: |
            **/tfplan-prod-*

  terraform_apply_job:
    name: Terraform Apply
    runs-on: [self-hosted]
    environment: infra-prod-cd
    needs: [terraform_preapply_job]

    steps:

      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110
        with:
          name: tfplan-output

      - name: Setup terraform
        id: setup-version
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/terraform/terraform-install-action
        uses: pagopa/eng-github-actions-iac-template/terraform/terraform-install-action@main

      - name: Terraform apply
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/terraform-apply-azure-action
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-apply-azure-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID_CD }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}
          azure_environment: prod
