name: Static Analysis

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .identity/**
      - .github/workflows/infra-static-analysis.yaml

jobs:
  static_analysis:
    runs-on: ubuntu-22.04

    steps:
      # from https://github.com/actions/checkout/commits/main
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: init_terraform_folders
        env:
          FOLDERS: >
            infra/src
            .identity
        run: |
          pids=()

          TAG=$(cat .terraform-version)
          for f in $FOLDERS; do
            pushd "$(pwd)/${f}"
              sed -i -e 's/  backend "azurerm" {}//g' main.tf # use local backend
              docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init &
              pids+=($!)
            popd
          done

          # Wait for each specific process to terminate.
          # Instead of this loop, a single call to 'wait' would wait for all the jobs
          # to terminate, but it would not give us their exit status.
          #
          for pid in "${pids[@]}"; do
            #
            # Waiting on a specific PID makes the wait command return with the exit
            # status of that process. Because of the 'set -e' setting, any exit status
            # other than zero causes the current shell to terminate with that exit
            # status as well.
            #
            wait "$pid"
          done

      - name: run_pre_commit_terraform
        run: |
          TAG="v1.83.6@sha256:f76cc7808f8f0f2dc06b7e9f8e5608bdb55416f00b436f6b581015a3d5fbe046"
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a -v && cat infra/src/README.md