name: Terraform plan multiregion

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"
      - ".github/workflows/infra-review-p.yml"

jobs:
  infra_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Terraform plan
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
      override_github_environment: infra-prod
