name: Terraform apply multiregion

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/prod/**"
      - "infra/_modules/**"
      - ".github/workflows/infra-review-p-itn.yml"

jobs:
  infra_release_prod_itn:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Terraform apply
    secrets: inherit
    with:
      environment: prod
      base_path: infra
      use_private_agent: true
