name: Terraform apply multiregion

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/prod/**"
      - "infra/_modules/**"
      - ".github/workflows/infra-release-p.yml"

jobs:
  infra_release_prod_itn:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@8fd8da4ece3ea29908b983fd8960366efb914253
    name: Terraform apply
    secrets: inherit
    with:
      environment: prod
      base_path: infra
      use_private_agent: true
