name: Run terraform plan on prod westeurope infrastructure

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci.yml'

permissions:
  id-token: write
  contents: read

env:
  DIR: 'infra/src'
  AZURE_ENVIRONMENT: prod

jobs:

  terraform_plan_job:
    name: Terraform Plan
    runs-on: [self-hosted]
    environment: prod-ci
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup terraform
        id: setup-version
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/terraform/terraform-install-action
        uses: pagopa/eng-github-actions-iac-template/terraform/terraform-install-action@main

      - name: Terraform plan
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/terraform-plan-azure-action
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-plan-azure-action@main
        with:
          client_id: ${{ secrets.ARM_CLIENT_ID }}
          tenant_id: ${{ secrets.ARM_TENANT_ID }}
          subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}
          azure_environment: prod
