name: Terraform apply multiregion

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"
      - ".github/workflows/infra-release-p.yml"

jobs:
  infra_release_prod_itn:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@cb9ee2230a521385a3b774d053c122c8b792541a
    name: Terraform apply
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
