name: Release

on:
  push:
    branches:
      - master
    paths:
      - .changeset/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: pagopa/dx/.github/workflows/release-v1.yaml@625f02f382c33eb449cd94facb8e426bf7ae37ea # main
    with:
      environment: release
    secrets:
      github-token: ${{ secrets.BOT_TOKEN }}
